-- Based on https://www.youtube.com/watch?v=SpexCBrZ1pQ&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ&index=15
--
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.impatient"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.nvim-colorizer"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.todo-comments"
